---

# Step 3 - Tear down the created instance(s).

- name: "Cleanup all instances that match the target tag - mysidlabs_owner: {{ siduser }}"
  hosts: localhost
  gather_facts: false

  tasks:

    - name: "Terminate labeled instances"
      ec2_instance:
        region: "{{ region }}"
        state: absent
        wait: false
        filters:
          "tag:mysidlabs_owner": "{{ siduser }}"
          "tag:mysidlabs": "1"

    - name: "Delete stale hosts inventory file"
      file:
        path: "{{ inventory_file }}"
        state: absent
...
