---

# Step 2 - Configure the instance.  This is a simple
# example that just creates a user acct and installs IIS and management tools.
#  This playbook can be extended to do more detailed configuration.

- name: "Configure Instance"
  hosts: all
  gather_facts: true

  tasks:

    - name: "Ensure User Account Exists"
      user:
        name: "{{ siduser }}"
        password: wind0wsSidLabs!
        groups: Administrators

    - name: Install IIS WebServer with sub-features and management tools
      win_feature:
        name: Web-Server
        state: present

...
