---
- name: "Dump hostinfo info"
  hosts: tag_mysidlabs_tier_web
  gather_facts: true

  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
          
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }} 
    
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info

      
#   tasks:
#     - debug:
#         msg:
#         - "ansible_distribution == {{ hostvars[inventory_hostname].ansible_distribution }}"
#         - "major version == {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
#         - "version == {{ hostvars[inventory_hostname].ansible_distribution_version }}"
# ...
