---
- name: install nssm
  win_chocolatey:
    name: nssm
    state: present
    
- name: install nginx
  win_chocolatey:
    name: nginx
    version: '1.19.1'
    state: present

- name: copy nginx conf file
  win_template: 
    src: nginx.conf.j2
    dest: C:\tools\nginx-1.19.1\conf\nginx.conf

- name: Open site's port on firewall
  win_firewall_rule:
    name: demo_app_80
    enable: yes
    state: present
    localport: 80
    action: Allow
    direction: In
    protocol: Tcp
    force: true
  tags: firewall

- name: restart nginx
  win_service:
    name: nginx
    state: restarted
...