---

# Step 3 - Tear down the created instance(s).

- name: "Cleanup all instances that match the target tag"
  hosts: localhost
  gather_facts: false
  vars:
    aws_profile: "{{ lookup('env', 'AWS_PROFILE') }}"
    siduser: "{{ lookup('env', 'MYSIDLABS_USER') }}"

  roles:
    - "{{ aws_profile }}_init"
    - env_check

  tasks:

    - name: "Terminate labeled instances"
      ec2_instance:
        state: absent
        wait: false
        filters:
          "tag:mysidlabs_owner": "{{ siduser }}"
          "tag:mysidlabs": "1"

    - name: "Delete stale hosts inventory file"
      file:
        path: "{{ inventory_file }}"
        state: absent
...
