---

# Step 2 - Configure the instance.  This is a simple
# example that just creates a user acct.  This playbook
# can be extended to do more detailed configuration.

- name: "Configure Instance"
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: "Ensure User Account Exists"
      user:
        name: "{{ siduser }}"
        groups: adm

    - name: "Add Authorized Key"
      authorized_key:
        user: "{{ siduser }}"
        key: "{{ lookup('file', '~/.ssh/ssh-key.pub') }}"

    - name: "Install a few sample packages"
      package:
        name:
          - git
          - vim
          - wget
        state: present
...
