---
- name: "Create host instance"
  hosts: localhost
  gather_facts: false

  tasks:

    - name: "Provision and launch instances"
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "ami-01e36b7901e884a10"
        instance_tags:
          Name: "{{ siduser }}-lab1"
          mysidlabs: "1"
          mysidlabs-tier: "ephemeral"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "lab1"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
        volumes:
        - device_name: /dev/sda1
          delete_on_termination: true
          volume_size: 8
          volume_type: standard
      register: result

    - name: "Remove old host inventory file"
      file:
        path: "inv.txt"
        state: absent
    
    - name: "Create hosts inventory file"
      lineinfile:
        create: true
        path: "inv.txt"
        line: "{{ result.instances[0].public_dns_name }}"

    - debug:
        msg: 
        - "{{ result.instances[0].tags.Name }}"
        - "Private IP: {{ result.instances[0].private_ip }}"
        - "Public IP: {{ result.instances[0].public_ip }}"
...
