---

# TODO
aws_ssh_key_pair: ansible-labs-only

instance_type: t2.micro

region: us-east-2

# TODO sg must be created
security_group: ssh-http-https

# TODO proper VPC must be used.  Store in group_vars?
vpc_subnet: "{{ lookup('env', 'VPC_SUBNET') or 'subnet-3964a275' }}"

...