---
- name: Wait for SSH
  hosts: "tag_mysidlabs_owner_{{ siduser }}"
  gather_facts: false
  tasks:
    - name: Wait for SSH
      wait_for_connection:
        delay: 60
        timeout: 300

- name: Configure Web Servers
  hosts: tag_mysidlabs_tier_web
  gather_facts: true
  roles:
    - web

- name: Configure Load Balancer
  hosts: tag_mysidlabs_tier_lb
  gather_facts: true
  roles:
    - lb
...

