---
- name: Create host instances
  hosts: localhost
  gather_facts: false
  vars:
    aws_ssh_key_pair: taranto-dev-aws
    instance_type: t2.micro
    region: us-east-2
    security_group: ssh-http-https
    siduser: "{{ lookup('env', 'MYSIDLABS_USER') }}"
    vpc_subnet: subnet-049a1c13e7b423b8c
  roles:
    - env_check

  tasks:

    - name: Provision and launch instances
      ec2:
        assign_public_ip: true
        group: "{{ security_group }}"
        image: "{{ item.ami }}"
        instance_tags:
          Name: "{{ siduser }}-{{ item.tier }}-{{ idx }}"
          mysidlabs: "1"
          mysidlabs_owner: "{{ siduser }}"
          mysidlabs_tier: "{{ item.tier }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ aws_ssh_key_pair }}"
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        wait: true
      loop:
        - { tier: "lb",  ami: "ami-0fc20dd1da406780b" } # Ubuntu
        - { tier: "web", ami: "ami-0e38b48473ea57778" } # ALX
        - { tier: "web", ami: "ami-0e38b48473ea57778" } # ALX
      loop_control:
        index_var: idx
      register: ec2

    - debug:
        msg: "{{ item.instances[0].tags.Name }} == {{ item.instances[0].private_ip }}, {{ item.instances[0].public_ip }}"
      loop: "{{ ec2.results }}"
      loop_control:
        label: ""
...

