---

- name: "Dump ec2 instance info"
  hosts: localhost
  gather_facts: false
  vars:
    # TODO
    aws_ssh_key_pair: ansible-labs-only
    instance_type: t2.micro
    region: us-east-2
    # TODO sg must be created
    security_group: ssh-http-https
    siduser: "{{ lookup('env', 'MYSIDLABS_USER') }}"
    # TODO proper VPC must be used.  Store in group_vars?
    vpc_subnet: subnet-3964a275

  # Quick check to make sure the runtime env looks reasonable.
  roles:
    - env_check

  tasks:

    - name: "Provision and launch instances"
      ec2_instance_info:
        filters:
          "tag:mysidlabs": "1"
      register: ec2

    - debug:
        msg: "{{ ec2 }}"
...
