---

- name: install-iis
  win_feature:
    name: "Web-Server"
    state: present
    restart: no
    include_sub_features: yes
    include_management_tools: yes

# - name: create staging path
#   win_file: path={{ staging_path }} state=directory

- name: default-website-index
  win_template:
    src: index.html
    dest: "C:\\inetpub\\wwwroot\\index.html"

# - name: create new website's directory
#   win_file: path={{ ansible_site_path }} state=directory

# - name: create new website
#   win_iis_website:
#     name: "Ansible Test Site"
#     state: started
#     port: 80
#     physical_path: "{{ ansible_site_path }}"

- name: Open site's port on firewall
  win_firewall_rule:
    name: demo_app_80
    enable: yes
    state: present
    localport: 80
    action: Allow
    direction: In
    protocol: Tcp
    force: true
  tags: firewall

# - name: create deploy staging path
#   win_file: path={{ ansible_test_staging_path }} state=directory

# - name: get code to deploy staging path
#   win_template:
#     # src: files/site.zip
#     src: index.html
#     dest: "{{ ansible_test_staging_path }}"

# - name: unzip code to site path
#   win_unzip:
#     src: "{{ ansible_test_staging_path }}\\site.zip"
#     dest: "{{ ansible_site_path }}"
#     creates: "{{ ansible_site_path }}\\index.html"
#   tags: unzip